//
//  APIConstants.swift
//  SMF-iOS
//
//  Created by Swapnil_Dhotre on 4/28/22.
//

import Foundation

class APIConstant {
    static let jwt_token = "jwt_token"
    static let auth = "Authorization"
    static let serviceCategoryId = "serviceCategoryId"
    static let serviceVendorOnboardingId = "serviceVendorOnboardingId"
    static let bidStatus = "bidStatus"
    static let bidRequestId = "bidRequestId"
    static let rejectedBidComment = "rejectedBidComment"
    static let rejectedBidReason = "rejectedBidReason"
    
    
    static var auth_token = "Bearer eyJraWQiOiI1OTV2RlJoWUZLeGVNZytYaU9kVGV1VE9nY1U3QmJWOGVZejlOWXZIcVlRPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJiNmQ2YTVhOS1iYWNhLTQ2YmYtOTBlZS1hMDhjZWIxMmUzYTkiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfV1ExU2RJbEM1IiwicGhvbmVfbnVtYmVyX3ZlcmlmaWVkIjp0cnVlLCJjb2duaXRvOnVzZXJuYW1lIjoiY2hhbjk3NzI5NWphaSIsIm9yaWdpbl9qdGkiOiI4ODVlMDliZC01MzkzLTRhNWYtOTU4Yy1hMDgwYzkxODdmNjAiLCJhdWQiOiI0cWhzc2UyaWQwYWE5YWFmcTlkNDdia2ZxcyIsImV2ZW50X2lkIjoiYmI3N2Y3ZDUtODg0OS00M2RmLTgzYmUtMGRjYzJhZDllYWM4IiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2NTM0NTg0MzYsIm5hbWUiOiJqYWkgY2hhbiIsInBob25lX251bWJlciI6Iis5MTg4NzAyMDMxNDEiLCJleHAiOjE2NTM0NjAyMzYsImlhdCI6MTY1MzQ1ODQzNiwianRpIjoiZGYxNThjYTEtYTY4ZC00YTJhLTlhODctNDQ4Zjc2N2ZkMWU1IiwiZW1haWwiOiJqYWljaGFuZGFyMTRAZ21haWwuY29tIn0.gEVSLtIO7ueFdy1-L3rSPoJv5XNx3_Qzbw9j206w-pOav-Ta074okt4JKYPSYLRjGsUbXw8EicniriYOXSPfm2vNJ55151ojVneStbxovq1KEvzw1Tw7nc-oFUNuVHN4YKpePtLRcziOmX2Hz8xJDqSd_4s89OlCij2uIaWHyzkC_QdMF6au2Bj-LwSUsYHeBs3VqxroDIAMASZPqL7VIn9OaunR1_vj0fvF-Xb3CchTgERgoWBIAEVZP3JvCg1cNwgZbs2rWABu1nfT58p0f2BsAHEdKSBtOr-lfy-5wtDdLB9PlUTRKKsgmkyhrfMIvB0Mum7or0rBhy4sXXwffQ"
}
