//
//  APIConstants.swift
//  SMF-iOS
//
//  Created by Swapnil_Dhotre on 4/28/22.
//

import Foundation

class APIConstant {
    static let jwt_token = "jwt_token"
    static let auth = "Authorization"
    static let serviceCategoryId = "serviceCategoryId"
    static let serviceVendorOnboardingId = "serviceVendorOnboardingId"
    static let bidStatus = "bidStatus"
    static let bidRequestId = "bidRequestId"
    static let rejectedBidComment = "rejectedBidComment"
    static let rejectedBidReason = "rejectedBidReason"
    
    
    static var auth_token = "Bearer eyJraWQiOiI1OTV2RlJoWUZLeGVNZytYaU9kVGV1VE9nY1U3QmJWOGVZejlOWXZIcVlRPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJiNmQ2YTVhOS1iYWNhLTQ2YmYtOTBlZS1hMDhjZWIxMmUzYTkiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfV1ExU2RJbEM1IiwicGhvbmVfbnVtYmVyX3ZlcmlmaWVkIjp0cnVlLCJjb2duaXRvOnVzZXJuYW1lIjoiY2hhbjk3NzI5NWphaSIsIm9yaWdpbl9qdGkiOiJhZDliNjZlMC01M2NmLTQ4MjItODZlNi1lM2U5MzcwMTA4ZTciLCJhdWQiOiI0cWhzc2UyaWQwYWE5YWFmcTlkNDdia2ZxcyIsImV2ZW50X2lkIjoiYTZlZWQxMGYtNGRmOC00NzYyLTg2YTktNmYwMzc3NDJmNzk1IiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2NTMzMTM5NjMsIm5hbWUiOiJqYWkgY2hhbiIsInBob25lX251bWJlciI6Iis5MTg4NzAyMDMxNDEiLCJleHAiOjE2NTMzMTU3NjMsImlhdCI6MTY1MzMxMzk2MywianRpIjoiNGYzNTE5OTEtZjFhZC00NWFjLWEwZWQtNDg5NTRjNTY1ZjA1IiwiZW1haWwiOiJqYWljaGFuZGFyMTRAZ21haWwuY29tIn0.jKcG6u0qMivP9VnQEZpdymgOjrKAS_G0tBCN2Ht-k9Ty0r10S4F-axKvi6Sq5SQRVVvkGIBgGwr7uWgz1-wjJz6mu1250skuOxVc5vr07a_xZDCH9PoDS2OmgEhfwWyVvlCxsXVRYO4Hc5_8VZyb23Ivksz6QL1TSsjsZkXcYdtyEpCOUGa9bFYP394CcGyzi6R5YJa7gQXlDOkpRROYGTjMcwR8tJxy4o29AfLnNTS7PWCBNjY_sJYt60UkeIbqpnfYCTMNmQxTdPCtWCV8-6WNSL2HEwaNPJR9lPIUc_MyEIuNYJouoNBZX0h98YIOw-gu62T83yM8sj3eMKNyyA"
}
